.TH MComix 1 "October 2020"

.SH NAME
.B MComix-Lite
\- Python3/GTK Manga Viewer

.SH SYNOPSIS
.B mcomix
.RI [ OPTION... "] [" PATH... ]

.SH DESCRIPTION
.B MComix-Lite
Is a specifically designed to handle Manga (and comics) and
supports a variety of container formats (including ZIP, 7Z, RAR, TAR, CBZ, CB7, CBR, and, CBT).

.SH OPTIONS
.TP
.BR -h , " --help"
Display the help text and exit.
.TP
.BR -v , " --version"
Show the version number and exit.
.PP
.B Viewing modes
.TP
.BR -f , " --fullscreen"
Start the application in fullscreen mode.
.TP
.BR -m , " --manga"
Start the application in manga mode.
.TP
.BR -d , " --double-page"
Start the application in double page mode.
.PP
.B Zoom modes
.TP
.BR -b , " --zoom-best"
Start the application with zoom set to best fit mode.
.TP
.BR -zw , " --zoom-width"
Start the application with zoom set to fit width.
.TP
.BR -zh , " --zoom-height"
Start the application with zoom set to fit height.
.PP
The zoom modes are mutually exclusive, and if more than one is specified,
the first will be used.
.PP
.B Debug
.TP
.BR -L , " --loglevel"
Levels: 'NONE', 'CRITICAL', 'ERROR', 'WARNING', 'INFO', 'VERBOSE', 'DEBUG', 'TRACE'
.TP

.SH ARGUMENTS
.TP
.I PATH
The path to one or more files or directories to be opened.

.SH DEPENDENCIES
.SS Required:
.B Python
3.8 or later
.PP
.B PyGObject
3.24 or later.
.PP
.B GTK+3
3.24 or later.
.PP
.B Pillow
Pillow 6.0.0 or later.
.SS Recommended:
.BR unrar
to extract RAR archives.
.PP
.B p7zip
to extract 7Z archives.
