[project]
name = 'mcomix-lite'
dynamic = ['version']
description = ''
requires-python = '>=3.12'

[build-system]
requires = [
    'meson-python',
]
build-backend = 'mesonpy'

[project.scripts]
mcomix = 'mcomix.main:main'

[tool.pytest.ini_options]
testpaths = [
    'tests',
]
