[project]
name = "mcomix-lite"
version = "3.4.0-dev"
description = ""
requires-python = ">=3.12"

[build-system]
requires = [
    "meson-python",
    "pybind11",
]
build-backend = "mesonpy"

[project.scripts]
mcomix = "mcomix.main:main"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
